// Curated historical context, reviewed against each linked publication.
// This is a non-exhaustive sample, not a claim that these events caused a
// particular company's return. Only explicit contemporaneous reporting is
// marked reported_driver. Market-wide reporting does not establish causation
// for an individual security. Publication dates have no invented intraday time.
export const REVIEWED_PRICE_EVENTS = [
  {
    id: 'meta-2024-02-01-first-dividend',
    symbols: ['META'],
    published_at: '2024-02-01',
    timing: 'date_only',
    title: 'Meta introduces a dividend and expands buybacks',
    summary: 'Alongside its fourth-quarter results, Meta declared its first quarterly dividend of $0.50 per share and added $50 billion to its repurchase authorization.',
    url: 'https://investor.atmeta.com/investor-news/press-release-details/2024/Meta-Reports-Fourth-Quarter-and-Full-Year-2023-Results-Initiates-Quarterly-Dividend/default.aspx',
    source: 'Meta Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'uber-2024-02-14-first-buyback',
    symbols: ['UBER'],
    published_at: '2024-02-14',
    timing: 'date_only',
    title: 'Uber authorizes its first share buyback',
    summary: 'Uber announced board authorization to repurchase up to $7 billion of its common shares, establishing the company\'s first share-repurchase program.',
    url: 'https://investor.uber.com/news-events/news/press-release-details/2024/Uber-Announces-Inaugural-7-Billion-Share-Repurchase-Authorization/',
    source: 'Uber Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'googl-2024-04-25-first-dividend',
    symbols: ['GOOGL', 'GOOG'],
    published_at: '2024-04-25',
    timing: 'date_only',
    title: 'Alphabet starts dividends and authorizes more buybacks',
    summary: 'Alphabet reported first-quarter revenue of $80.5 billion, introduced a $0.20-per-share cash dividend, and authorized an additional $70 billion in share repurchases.',
    url: 'https://www.sec.gov/Archives/edgar/data/1652044/000165204424000047/googexhibit991q12024.htm',
    source: 'Alphabet earnings release via SEC',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'amzn-2024-04-30-q1-earnings',
    symbols: ['AMZN'],
    published_at: '2024-04-30',
    timing: 'date_only',
    title: 'Amazon reports higher sales and operating profit',
    summary: 'Amazon reported first-quarter sales of $143.3 billion and operating income of $15.3 billion. AWS revenue grew 17% year over year to $25.0 billion.',
    url: 'https://ir.aboutamazon.com/news-release/news-release-details/2024/Amazon-com-Announces-First-Quarter-Results-68b9258cd/default.aspx',
    source: 'Amazon Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'nvda-2024-05-22-q1-split',
    symbols: ['NVDA'],
    published_at: '2024-05-22',
    timing: 'date_only',
    title: 'NVIDIA reports AI growth and announces stock split',
    summary: 'NVIDIA reported fiscal first-quarter revenue of $26.0 billion, 262% above the prior year, and announced a ten-for-one stock split and higher dividend.',
    url: 'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2025',
    source: 'NVIDIA Newsroom',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'aapl-2024-06-10-apple-intelligence',
    symbols: ['AAPL'],
    published_at: '2024-06-10',
    timing: 'date_only',
    title: 'Apple unveils Apple Intelligence',
    summary: 'Apple introduced generative AI features for iPhone, iPad, and Mac, including writing tools, image creation, a redesigned Siri, and planned ChatGPT integration.',
    url: 'https://www.apple.com/newsroom/2024/06/introducing-apple-intelligence-for-iphone-ipad-and-mac/',
    source: 'Apple Newsroom',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'googl-2024-08-05-search-ruling',
    symbols: ['GOOGL', 'GOOG'],
    published_at: '2024-08-05',
    timing: 'date_only',
    title: 'Court rules against Google in search antitrust case',
    summary: 'The Justice Department announced a court victory in its antitrust case against Google, publishing statements from Attorney General Garland and antitrust chief Jonathan Kanter.',
    url: 'https://www.justice.gov/archives/opa/pr/justice-department-statements-us-district-court-district-columbias-decision-us-v-google',
    source: 'U.S. Department of Justice',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'tsla-2025-04-02-q1-deliveries',
    symbols: ['TSLA'],
    published_at: '2025-04-02',
    timing: 'date_only',
    title: 'Tesla releases first-quarter delivery figures',
    summary: 'Tesla reported more than 336,000 vehicle deliveries and 10.4 GWh of energy-storage deployments for the first quarter, noting production effects from its Model Y changeover.',
    url: 'https://ir.tesla.com/press-release/tesla-first-quarter-2025-production-deliveries-and-deployments',
    source: 'Tesla Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'market-2025-04-02-reciprocal-tariffs',
    symbols: ['*'],
    published_at: '2025-04-02',
    timing: 'date_only',
    title: 'White House announces broad import tariffs',
    summary: 'The White House announced a 10% baseline import tariff, higher country-specific rates, and exemptions, with implementation dates of April 5 and April 9.',
    url: 'https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-declares-national-emergency-to-increase-our-competitive-edge-protect-our-sovereignty-and-strengthen-our-national-and-economic-security/',
    source: 'The White House',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'market-2025-04-09-tariff-pause-rally',
    symbols: ['*'],
    published_at: '2025-04-09',
    timing: 'date_only',
    title: 'U.S. stocks rally following tariff-pause announcement',
    summary: 'Reuters attributed a broad U.S. stock rally to the announced 90-day tariff pause, while reporting a retained 10% baseline and higher tariffs on China.',
    url: 'https://www.investing.com/news/economy-news/stocks-rally-on-trump-tariff-pause-after-market-rout-3977563',
    source: 'Reuters via Investing.com',
    relationship: 'reported_driver',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'msft-2025-04-30-fy25-q3',
    symbols: ['MSFT'],
    published_at: '2025-04-30',
    timing: 'date_only',
    title: 'Microsoft reports Azure growth in quarterly results',
    summary: 'Microsoft reported fiscal third-quarter revenue of $70.1 billion, up 13% year over year, with Azure and other cloud services revenue rising 33%.',
    url: 'https://www.microsoft.com/en-us/investor/earnings/FY-2025-Q3/press-release-webcast',
    source: 'Microsoft Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'meta-2025-04-30-q1-capex',
    symbols: ['META'],
    published_at: '2025-04-30',
    timing: 'date_only',
    title: 'Meta reports growth and raises capital-spending outlook',
    summary: 'Meta reported first-quarter revenue of $42.3 billion and raised its 2025 capital-spending outlook to $64–72 billion, citing AI infrastructure investment and hardware costs.',
    url: 'https://investor.atmeta.com/investor-news/press-release-details/2025/Meta-Reports-First-Quarter-2025-Results/',
    source: 'Meta Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'msft-2026-01-28-fy26-q2',
    symbols: ['MSFT'],
    published_at: '2026-01-28',
    timing: 'date_only',
    title: 'Microsoft reports fiscal second-quarter cloud results',
    summary: 'Microsoft reported fiscal second-quarter revenue of $81.3 billion, 17% above the prior year, while Azure and other cloud services revenue increased 39%.',
    url: 'https://www.microsoft.com/en-us/investor/earnings/fy-2026-q2/press-release-webcast',
    source: 'Microsoft Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'aapl-2026-01-29-fy26-q1',
    symbols: ['AAPL'],
    published_at: '2026-01-29',
    timing: 'date_only',
    title: 'Apple reports record December-quarter revenue',
    summary: 'Apple reported fiscal first-quarter revenue of $143.8 billion, up 16% year over year, with record iPhone and Services sales and diluted earnings of $2.84 per share.',
    url: 'https://www.apple.com/newsroom/2026/01/apple-reports-first-quarter-results/',
    source: 'Apple Newsroom',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'amzn-2026-02-05-q4-capex',
    symbols: ['AMZN'],
    published_at: '2026-02-05',
    timing: 'date_only',
    title: 'Amazon reports results and outlines investment plans',
    summary: 'Amazon reported fourth-quarter sales of $213.4 billion and said it expected about $200 billion in capital expenditures across the company during 2026.',
    url: 'https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Fourth-Quarter-Results/default.aspx',
    source: 'Amazon Investor Relations',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
  {
    id: 'nvda-2026-02-25-fy26-q4',
    symbols: ['NVDA'],
    published_at: '2026-02-25',
    timing: 'date_only',
    title: 'NVIDIA reports fiscal-year and quarterly records',
    summary: 'NVIDIA reported fiscal fourth-quarter revenue of $68.1 billion, up 73% year over year, with data-center revenue of $62.3 billion and annual revenue of $215.9 billion.',
    url: 'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-fourth-quarter-and-fiscal-2026',
    source: 'NVIDIA Newsroom',
    relationship: 'context',
    reviewed_at: '2026-10-08',
  },
];
