"""Regenerate the owner-only source catalogue after calculation changes."""
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
paths = set()
for path in (root / 'services/api').rglob('*.py'):
    if 'legacy' not in path.parts and not path.name.startswith('test_'):
        paths.add(path)
paths.update((root / 'apps/terminal/public').glob('terminal*.js'))
paths.add(root / 'apps/terminal/public/equity-workbook-model.js')
paths.update(path for path in (root / 'supabase/functions/wave-data').glob('*.ts')
             if path.name != 'calculation-catalog.ts' and '.test.' not in path.name)
catalog = [{'path': str(path.relative_to(root)), 'source': path.read_text()}
           for path in sorted(paths)]
target = root / 'supabase/functions/wave-data/calculation-catalog.ts'
target.write_text('// Generated by scripts/build-calculation-catalog.py; do not edit manually.\n'
                  + 'export const SOURCE_CATALOG = '
                  + json.dumps(catalog, ensure_ascii=False, separators=(',', ':')) + ';\n')
print(f'Indexed {len(catalog)} source files')
